defaults:
  - dataset: VCDataset
  - model: HiFiVC
  - _self_
G_optimizer:
  _target_: src.optimizer.ExtraAdam
  lr: 5e-5
  betas: [0.5, 0.9]
D_optimizer:
  _target_: src.optimizer.ExtraAdam
  lr: 5e-4
  betas: [0.5, 0.9]
G_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1
D_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1
G_loss_function:
  _target_: src.loss.GeneratorLoss
  fm_coef: 1
  mel_coef: 45
  kl_coef: 0.01
D_loss_function:
  _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 50
  batch_size: 16
  num_workers: 2
  n_epochs: 100
  epoch_len: 500
  run_name: "testing"
  override: false
  generator_only: ${model.generator_only}